// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NavigationPlatform.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NavigationPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260110110110_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NavigationPlatform.Domain.Journeys.Journey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArrivalLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arrival_location");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrival_time");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("distance_km");

                    b.Property<bool>("IsDailyGoalAchieved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_daily_goal_achieved");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_location");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transport_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("journeys", (string)null);
                });

            modelBuilder.Entity("NavigationPlatform.Infrastructure.Persistence.Audit.JourneyShareAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JourneyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("journey_share_audits", (string)null);
                });

            modelBuilder.Entity("NavigationPlatform.Infrastructure.Persistence.Favourites.JourneyFavourite", b =>
                {
                    b.Property<Guid>("JourneyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("JourneyId", "UserId");

                    b.ToTable("journey_favourites", (string)null);
                });

            modelBuilder.Entity("NavigationPlatform.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("processed");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Processed");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("NavigationPlatform.Infrastructure.Persistence.Sharing.JourneyPublicLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JourneyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("journey_public_links", (string)null);
                });

            modelBuilder.Entity("NavigationPlatform.Infrastructure.Persistence.Sharing.JourneyShare", b =>
                {
                    b.Property<Guid>("JourneyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SharedWithUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SharedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JourneyId", "SharedWithUserId");

                    b.ToTable("journey_shares", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
